name: Publish
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      generator-service:
        image: cmgriffing/gilfold-openapi-client-generator:skipper
        ports:
          - 8888:8080

    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 6.0.2
      - run: "ls && pnpm generate:script:ci"
