name: Publish
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      generator:
        image: cmgriffing/gilfold-openapi-client-generator:skipper
        ports:
          - 8888:8080

    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 6.0.2
      - run: pnpm install
      - run: "ls && pnpm generate:script:ci"
      - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          add: "./clients -f"
          # commit: ""
          default_author: github_actions
          message: "SDK Release commit via GitHub Actions"

          # The arguments for the `git rm` command (see the paragraph below for more info)
          # Default: ''
          remove: "./sdks -r"

          # Arguments for the git tag command (the tag name always needs to be the first word not preceded by an hyphen)
          # Default: ''
          # tag: "v1.0.0 --force"

          # Arguments for the git push --tags command (any additional argument will be added after --tags)
          # Default: ''
          # tag_push: "--force"
